profile:
    - name: Profile 1
      user: メールアドレス
      pass: パスワード

      price:
          down_step: 100 # 1回あたりの値下げ幅〔円〕
          threshold: 3000 # 値下げを止める価格〔円〕
      interval:
          hour: 20 # 更新時間がこの時間より短い場合，スキップ

# 動作ログをメールで送信する場合，以下を設定
# mail:
#   user:
#   pass:
#   from:
#   to:
#   subject:

# 動作ログを Slack で通知する場合，以下を設定
# slack:
#   bot_token:
#   info:
#     channel: "#mercari"
#   error:
#     channel: "#error"
#     interval_min: 180

slack:
    bot_token: xoxp-XXXXXXXXXXXX-XXXXXXXXXXXX-XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    from: Mercari Bot

    info:
        channel: "#mercari"

    captcha:
        channel:
            name: "#captcha"
            id: XXXXXXXXXXX

    error:
        channel:
            name: "#error"
            id: XXXXXXXXXXX
        interval_min: 180
