user: メールアドレス
pass: パスワード

# SMTP server login and mailing address
mail:
  user:
  pass:
  from:
  to:
  subject:

price:
    down_step: 100      # 1回あたりの値下げ幅〔円〕
    threshold: 3000     # 値下げを止める価格〔円〕
